### ISSUE TITLE
How can i distinguish a specific recording between those recordings which are being triggered at same time

### ISSUE THREAD

**Issue by rnqayush** [aws-samples/amazon-chime-sdk-recording-demo#103]
I have a react native app for video meeting and implemented chime-sdk-recording in it.
I am able to start recording and after stopping, It is getting stored in s3 bucket.
Also through node.js i am able to get the recording url and able to download it.

My Issue:

I am having two or more recordings started at same time through my app which is getting stored in s3. i want to distinguish a specific recording between those recordings which are being triggered at same time.

Kindly suggest some idea to solve it

**Comment by jing-chen1** [comment]
Hi @rnqayush, Chime SDK team has launched a new service to provide meeting capture capabilities with original video resolution and frame rate. You will not need to provision your own container infrastructure. Instead, just call the API from AWS SDK and provide a prepared S3 bucket to receive the artifacts.

You can use the attendee ID to distinguish a specific recording, as the name format of the video stored in S3 is `yyyy-MM-dd-HH-mm-ss-SSS-[ATTENDEE-ID]#content.mp4.`. To know more, please check out the blog: [Capture Amazon Chime SDK Meetings Using Media Capture Pipelines](https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/)

**Comment by rnqayush** [comment]
@jing-chen1 thanks for your response, Actually i am using old service and recordings are being saved s3 in the format of yyyy-MM-dd-HH-mm-ss.mp4. Kindly suggest some idea through old service to distinguish a specific recording

**Comment by rnqayush** [comment]
![skype](https://user-images.githubusercontent.com/74084740/127682809-8f0ef61d-b736-4617-ad45-6930821fac21.png)

**Comment by anuranduttaroy** [comment]
Hey @rnqayush, here is the line where we are deciding the file name [record.js#L76](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L76). If you want, you can use a more friendly name here.

Let me know if this helps.

**Comment by rnqayush** [comment]
@anuranduttaroy thanks but my issue is if two meetings with meetingId 'A' and  'B' got started at same time and date then how will i distinguish between both the recordings in s3 bucket which one is meeting 'A' without playing recording video

**Comment by rnqayush** [comment]
@anuranduttaroy  can we  pass meeting url https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/f3f65d94a59067c4454d6d73cb2e671c68d44a47/recording/record.js#L7 while deciding file name .

**Comment by tenge-amzn** [comment]
Hi @rnqayush 

Chime SDK team has launched a new service to provide meeting capture capabilities with original video resolution and frame rate. You will not need to provision your own container infrastructure. Instead, just call the API from AWS SDK and provide a prepared S3 bucket to receive the artifacts.

To know more, please check out the blog:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

**Comment by rnqayush** [comment]
@jing-chen1  i am using old service and recordings are being saved s3 in the format of yyyy-MM-dd-HH-mm-ss.mp4. Kindly suggest some idea through old service to distinguish a specific recording

**Comment by anuranduttaroy** [comment]
Hey @rnqayush, as mentioned [here](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/103#issuecomment-890091803), you can append the meeting-id or some other unique identifier that you choose to in the file name to distinguish the recordings stored in s3. 

Adding the URL or part of it to the file name as you mentioned [here](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/103#issuecomment-890105413) also should work.

Let me know if that helps.

**Comment by anuranduttaroy** [comment]
Hey @rnqayush feel free to re-open this issue if you still have questions.
