### ISSUE TITLE
Recording not starting

### ISSUE THREAD

**Issue by rohittb** [aws-samples/amazon-chime-sdk-recording-demo#113]
Hello

 we have implemented recording solution in our solution. its working fine till 31st march . while we checked it on 1st april recording is not starting. As we check the api its return task id but recorder not able to join the meeting.

**Comment by yuqil-amzn** [comment]
Hi,
Could you please share more info to us? For example, the meeting id and media pipeline id. Also, could you please check if the s3 bucket policy is setup correctly?

Thanks

**Comment by yuqil-amzn** [comment]
Hi,
Could you please confirm the sdk version you use? There is a new version release on 30th. This might be related to your issue.

Thanks

**Comment by michhyun1** [comment]
@rohittb I see no response, will close this issue. Please contact us again if you have more questions.
