### ISSUE TITLE
Media Concatenation Pipeline not Working

### ISSUE THREAD

**Issue by coderb0yakash** [aws-samples/amazon-chime-sdk-recording-demo#114]
I am using aws-sdk/client-chime-sdk-media-pipelines SDK with node js server . I was able create all other features related to WebRTC calling. When I recording the call, files are getting stored with 5 sec small audio/video files in my S3 bucket. But when I am trying to merge the recordings as per the documentation it's not working. I am passing the ID and with the id I am locating the media path . I get a success response when I run the  `CreateMediaConcatenationPipelineCommand` command but I am not getting the merged audio output files.  Below is my  media concatenation code . I have tried changing my arn .Also I have tried running this command after the meeting ends still not working. Please help me to fix this. Thanks
```
const mergeRecording = async (req, res, next) => {
    const { id } = req.body;
    try {
        const client = new ChimeSDKMediaPipelinesClient(config);
        const input =
        {
            Sinks: [
                {
                    S3BucketSinkConfiguration: { Destination: "arn:aws:s3:::xxxxxxx/chime/" },
                    Type: 'S3Bucket',
                },
            ],
            Sources: [
                {
                    MediaCapturePipelineSourceConfiguration: {
                        ChimeSdkMeetingConfiguration: {
                            ArtifactsConfiguration: {
                                Audio: { State: 'Enabled' },
                                CompositedVideo: { State: 'Enabled' },
                                Content: { State: 'Enabled' },
                                DataChannel: { State: 'Disabled' },
                                MeetingEvents: { State: 'Disabled' },
                                TranscriptionMessages: { State: 'Disabled' },
                                Video: { State: 'Enabled' },
                            },
                        },
                        // MediaPipelineArn: `arn:aws:s3:::xxxxxxx/chime-meetings/${id}`, //earlier I was trying with this
                        MediaPipelineArn: `arn:aws:chime:us-east-2:460xxxxx1460:media-pipeline/${id}`,
                    },
                    Type: 'MediaCapturePipeline',
                },
            ],
        };
        const command = new CreateMediaConcatenationPipelineCommand(input);
        const response = await client.send(command);

        return res.json({ response: response, success: true, code: 200 })
    } catch (error) {
        return res.json({ error: error, success: false, code: 500 })
    }
}
```

**Comment by AndrewSNL** [comment]
Hi, can you please provide the failed media-pipeline-id for us to investigate?

**Comment by sinanliuAmazon** [comment]
Hi @coderb0yakash , can you please provide the failed media-pipeline-id for us to investigate?

**Comment by coderb0yakash** [comment]
media-pipeline-id: 360689c5-ded3-4f90-b6da-3dfbe3a485b4

**Comment by coderb0yakash** [comment]
{
    "response": {
        "$metadata": {
            "httpStatusCode": 200,
            "requestId": "7af4694c-8029-44db-b92f-5d2d5cc5821d",
            "attempts": 1,
            "totalRetryDelay": 0
        }
    },
    "success": true,
    "code": 200
}{
    "response": {
        "$metadata": {
            "httpStatusCode": 200,
            "requestId": "7af4694c-8029-44db-b92f-5d2d5cc5821d",
            "attempts": 1,
            "totalRetryDelay": 0
        }
    },
    "success": true,
    "code": 200
}

I got this from CreateMediaConcatenationPipelineCommand

**Comment by sinanliuAmazon** [comment]
I looked up the record for media-pipeline-id, `360689c5-ded3-4f90-b6da-3dfbe3a485b4` is a media capture pipeline, not media concatenation pipeline. I also checked request-id `7af4694c-8029-44db-b92f-5d2d5cc5821d` in us-east-1 region, it is not from our service. Can you please double check the code and see if it is actually making the API call for create-media-concatenation-pipeline?

**Comment by coderb0yakash** [comment]
HI @sinanliuAmazon  I used the above code  const command = new CreateMediaConcatenationPipelineCommand(input);
        const response = await client.send(command); and console the response I got this data
        `CreateMediaConcatenationPipelineCommandResponse {
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'f59b0f28-7414-4de3-9051-e5c50e3406ae',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}`

If this is not the data you are expecting please let me know I add you to the codebase we are using

**Comment by coderb0yakash** [comment]
HI @sinanliuAmazon When I Started the media capture pipiline command I got this response

`{"success":true,"response":{"$metadata":{"httpStatusCode":201,"requestId":"fabcb441-dff1-421d-ac10-bdc91450766b","attempts":1,"totalRetryDelay":0},"MediaCapturePipeline":{"ChimeSdkMeetingConfiguration":{"ArtifactsConfiguration":{"Audio":{"MuxType":"AudioWithActiveSpeakerVideo"},"Content":{"MuxType":"ContentOnly","State":"Enabled"},"Video":{"MuxType":"VideoOnly","State":"Enabled"}}},"CreatedTimestamp":"2023-04-05T11:50:56.876Z","MediaPipelineId":"606cde9d-7b57-4f6e-8c4c-f29dabd974de","SinkArn":"arn:aws:s3:::mentorpeak-prod-2/chime-meetings/7061d29b-b63d-4f07-bedb-400ee2930706","SinkType":"S3Bucket","SourceArn":"arn:aws:chime::460997161460:meeting:7061d29b-b63d-4f07-bedb-400ee2930706","SourceType":"ChimeSdkMeeting","Status":"Initializing","UpdatedTimestamp":"2023-04-05T11:50:56.953Z"}},"code":200,"message":"Recording Started!","result":true}`

Now here I suppose to receive the pipeline arn but I am not getting the data

As per doc I am using the above pipeline id to get the GetMediaPipelineCommand but not getting any data


but if i use GetMediaCapturePipelineCommand then I get this response 


`{
	"success": true,
	"response": {
		"$metadata": {
			"httpStatusCode": 200,
			"requestId": "7ab5b672-6bb7-49b1-ab5d-fd492d2e085b",
			"attempts": 1,
			"totalRetryDelay": 0
		},
		"MediaCapturePipeline": {
			"ChimeSdkMeetingConfiguration": {
				"ArtifactsConfiguration": {
					"Audio": {
						"MuxType": "AudioWithActiveSpeakerVideo"
					},
					"Content": {
						"MuxType": "ContentOnly",
						"State": "Enabled"
					},
					"Video": {
						"MuxType": "VideoOnly",
						"State": "Enabled"
					}
				}
			},
			"CreatedTimestamp": "2023-04-05T11:40:52.473Z",
			"MediaPipelineId": "d8e615f3-5ec1-45d1-8441-5b83679f0afd",
			"SinkArn": "arn:aws:s3:::mentorpeak-prod-2/chime-meetings/7061d29b-b63d-4f07-bedb-400ee2930706",
			"SinkType": "S3Bucket",
			"SourceArn": "arn:aws:chime::460997161460:meeting:7061d29b-b63d-4f07-bedb-400ee2930706",
			"SourceType": "ChimeSdkMeeting",
			"Status": "InProgress",
			"UpdatedTimestamp": "2023-04-05T11:40:52.968Z"
		}
	}
}`

I am create a repo to attach my code so that you can easily figure out anything wrong with it please use this link https://github.com/coderb0yakash/chime.git

**Comment by coderb0yakash** [comment]
Hi @sinanliuAmazon now I am able to get the response properly after updating the sdk versions

`{
	"error": {
		"name": "BadRequestException",
		"$fault": "client",
		"$metadata": {
			"httpStatusCode": 400,
			"requestId": "964cb34b-0845-4d2d-9620-bd195234225f",
			"attempts": 1,
			"totalRetryDelay": 0
		},
		"Code": "BadRequest",
		"RequestId": "964cb34b-0845-4d2d-9620-bd195234225f",
		"message": "S3 Bucket policy not valid"
	},
	"success": false,
	"code": 500
}`

now this is last thing which is not working we tried to update the policy

but got error 

![image_2023_04_05T13_54_55_672Z](https://user-images.githubusercontent.com/126647050/230103133-c856de42-033b-4245-aaf6-203d1f33b399.png)
****

**Comment by sinanliuAmazon** [comment]
Hi @coderb0yakash , for resource defined under "AWSChimeMediaCaptureBucketPolicy", you will need something like
```
            "Resource": [
                "arn:aws:s3:::my-private-bucket/*",
                "arn:aws:s3:::my-private-bucket",
            ],
```

"s3:ListBucket" action requires permission on the bucket. The other actions require permission on the objects in the bucket. You must use two different Amazon Resource Names (ARNs) to specify bucket-level and object-level permissions. See https://docs.aws.amazon.com/chime-sdk/latest/dg/create-concat-pipe-steps.html for details.

Not specific to your original question, but in case you need to use customer managed key on the S3 bucket, please refer to https://docs.aws.amazon.com/chime-sdk/latest/dg/sse-kms.html#customer-key for details. In short, you will need to add `kms:GenerateDataKey` and `kms:Decrypt` permission for `mediapipelines.chime.amazonaws.com` service principle in the KMS key policy.

**Comment by coderb0yakash** [comment]
Hi @sinanliuAmazon I am using this artifact conf
`ArtifactsConfiguration: {
                Audio: { State: 'Enabled' },
                CompositedVideo: { State: 'Enabled' },
                Content: { State: 'Disabled' },
                DataChannel: { State: 'Enabled' },
                MeetingEvents: { State: 'Enabled' },
                TranscriptionMessages: { State: 'Enabled' },
                Video: { State: 'Disabled' },
              }`
video do not have any audio in audio folder there is an mp4 of audio I am looking for an single video where all content audio and videos will be available

**Comment by sinanliuAmazon** [comment]
Closing the issue since all questions are answered, feel free to re-open if any further questions.
