### ISSUE TITLE
Failed to create/update the stack

### ISSUE THREAD

**Issue by ginishajasmingj** [aws-samples/amazon-chime-sdk-recording-demo#116]
Error: Failed to create/update the stack: tymeplus-live, Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "UPDATE_ROLLBACK_COMPLETE" at least once

**Comment by MingcongQi** [comment]
for the recording, I would suggest you use media capture pipeline,
the blog: https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
API: https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaCapturePipeline.html
Serverless demo Media Capture: https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/serverless

**Comment by anuranduttaroy** [comment]
@ginishajasmingj feel free to re-open the issue if you still have questions.
