### ISSUE TITLE
exec /recording/run.sh: exec format error

### ISSUE THREAD

**Issue by bao-uptempo** [aws-samples/amazon-chime-sdk-recording-demo#119]
I got this error when POST to start recording in 
`CloudWatch > Log groups > recording-demo-container/recording-demo-container/81f3ca5741594f249ce687ef87d0156c`
how to resolve it?

<img width="727" alt="Screen Shot 2024-06-14 at 23 20 38" src="https://github.com/aws-samples/amazon-chime-sdk-recording-demo/assets/126232919/cd6f214c-3cde-4541-8283-600248b0a2cb">

**Comment by MingcongQi** [comment]
One possibility was you were using a container whose architecture was different with Image.

**Comment by bao-uptempo** [comment]
> One possibility was you were using a container whose architecture was different with Image.

Hi @MingcongQi , sorry but can you explain your think more clearly?
