### ISSUE TITLE
tag key cannot be updated by your account

### ISSUE THREAD

**Issue by shijinbharati** [aws-samples/amazon-chime-sdk-recording-demo#13]
node ./deploy.js -b <my-bucket> -s <my-stack> -i <my-docker-image-uri> -r <region>
command failed with the following exception

```
Deploying recording application

        Deploying with following values
        ===============================
        Stack name                 : aws-cloud9-xxx-xxx-xxxxxx
        Region                     : eu-west-2
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_IAM"]
        Parameter overrides        : {'ECRDockerImageArn': 'yyyyyyyyyyyyy.dkr.ecr.eu-west-2.amazonaws.com/chimerecording:latest'}

Initiating deployment
=====================

Command sam failed with exit code 1 signal null
Error: Failed to create changeset for the stack: aws-cloud9-xxx-xxx-xxxxxx, An error occurred (ValidationError) when calli
```
The IAM user has permission attached to the image.
![lpS0r](https://user-images.githubusercontent.com/3006777/81578009-e05a2300-93c7-11ea-8a48-65592ba0bd5e.png)
What changes need to make to fix the issue?

**Comment by davidilieberman** [comment]
Having the same issue. Any luck?

**Comment by shijinbharati** [comment]
> Having the same issue. Any luck?

No, I  was stuck.

**Comment by davidilieberman** [comment]
I got it partially working in us-east-1. I think in m case this may have been caused by a few different users in the same account trying to do the tutorial at the same time. I've been able to complete the setup work and start meetings, but no recordings appear in the output bucket, even after a few hours time after the recording is stopped.

**Comment by shijinbharati** [comment]
I was tried eu-west-2 , but not working

**Comment by shijinbharati** [comment]
> I got it partially working in us-east-1. I think in m case this may have been caused by a few different users in the same account trying to do the tutorial at the same time. I've been able to complete the setup work and start meetings, but no recordings appear in the output bucket, even after a few hours time after the recording is stopped.

I was tried eu-west-2 , but not working

**Comment by comet-hale** [comment]
Same issue..
```
Initiating deployment
=====================

Command sam failed with exit code 1 signal null
Error: Failed to create changeset for the stack: chime-demo, An error occurred (ValidationError) when calling the CreateChangeSet operation: AccessDenied. User doesn't have permission to call ssm:GetParameters
```

**Comment by anuranduttaroy** [comment]
This seems like a could9 issue. I tried to create a cloud9 instance in `eu-west-2` and tried to deploy the recording application and it worked fine for me. Make sure your cloud9 environment is also in the same region where you are trying to deploy the recording app.

Also, can you try logging into your AWS account with **AdministratorAccess** policy and see if you get the same error?

**Comment by anuranduttaroy** [comment]
@shijinbharati let us know if the issue still persists.

**Comment by shijinbharati** [comment]
@anuranduttaroy   Due to that issue, we are not developing that application. I will try the suggestions, Thank you

**Comment by kawaljee** [comment]
@anuranduttaroy Even we are getting the same issue. Could you please help us resolve it?
