### ISSUE TITLE
Where Should i get Meeting URL?

### ISSUE THREAD

**Issue by koni-a** [aws-samples/amazon-chime-sdk-recording-demo#14]
Hi Team,

Where should I get a meeting URL, to pass when the recording starts.

Below are the parameters we are getting when the meeting created 

	public class Meeting
    {
        public Meeting();
        public MediaPlacement MediaPlacement { get; set; } 
        public string MediaRegion { get; set; }  
        public string MeetingId { get; set; }
    }

	public class MediaPlacement
    {
        public MediaPlacement();
 
        public string AudioFallbackUrl { get; set; } 
        public string AudioHostUrl { get; set; } 
        public string ScreenDataUrl { get; set; } 
        public string ScreenSharingUrl { get; set; } 
        public string ScreenViewingUrl { get; set; } 
        public string SignalingUrl { get; set; } 
        public string TurnControlUrl { get; set; }
    }

can u please tell me the steps.

Thanks

**Comment by anuranduttaroy** [comment]
The URL should be of the app that is developed using the [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js). 

For example, if you deploy the [serverless demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) by following the instructions given in the [README](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless#run-deployment-script), you would get an URL similar to `https://abcdefghij.execute-api.us-east-1.amazonaws.com/Prod/v2`. You can start a meeting and use the meeting URL to start the recording.

**Comment by aburnson** [comment]
Yes, since this demo records the entire web application, it needs to know the URL of the page to load when recording. This is admittedly a little unclear from the README. Labeling as documentation, so we can make that more clear.
