### ISSUE TITLE
Recording bot never joins meeting

### ISSUE THREAD

**Issue by davidilieberman** [aws-samples/amazon-chime-sdk-recording-demo#16]
After several attempts, I was able to complete the setup and start a meeting, using Postman to start and stop the recording process as recommended. I have now run the demo a few times and what I've realized is the recording bot is never joining the meeting, although I do receive a 200 response from the API Post with recordingAction=start. I've tried using both versions of the meeting URL generated from the second Node script. I can login in as a participant with either URL, but the recording bot never shows up.

**Comment by nagydniel** [comment]
Can you attach the logs from the ECS task? 

On the ECS Clusters page, Select your cluster, click on Tasks, you will see one task running, click on its ID, and click on logs.

**Comment by bvsubhash** [comment]
Hi @nagydniel 
My Chime meeting URL is as follows: https://chime.aws/<meetingID>
I tried this project today and the recording mp4 file was created successfully in S3 as well. Interestingly, this is what I observed after looking into the recorded video.

<img width="1678" alt="Chime bot recording" src="https://user-images.githubusercontent.com/8126926/84423713-85bd1c80-ac3c-11ea-9549-852ce389182a.png">

The firefox browser inside ECS is getting stuck at following page requesting for the Display name and hence it is unable to join into the meeting. Should we need to pass any parameters to the following code of line in run.sh under recordings folder to fix this issue?
`BROWSER_URL="${MEETING_URL}&record=true"`

**Comment by bvsubhash** [comment]
Few minutes back, I realised that we have to provide the SDK Application URL as input instead of Chime meeting url and also that we have to pass the meeting name as query parameter in SDK Application URL. Hence, issued a PR to update README with example meetingURL.

**Comment by anuranduttaroy** [comment]
We updated the documentation with PR https://github.com/aws-samples/amazon-chime-sdk-recording-demo/pull/23 to indicate how the meeting URL should look like in [Start an Amazon Chime SDK meeting with our serverless demo and join with multiple participants](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#start-an-amazon-chime-sdk-meeting-with-our-serverless-demo-and-join-with-multiple-participants) section of the README. 

Also, if you see our serverless demo app v2 code [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L163-L171), it checks whether its a regular participant or a recording bot based upon `record=true` query parameter & programmatically fills in the name of the `bot` as `«Meeting Recorder»` and joins the meeting. You need to have a similar mechanism in your application for the bot to authenticate/bypass authentication and join the meeting to start the recording.
