### ISSUE TITLE
firefox crash when audio plays

### ISSUE THREAD

**Issue by OliverwengFiltered** [aws-samples/amazon-chime-sdk-recording-demo#27]
Hi aws chime recording support.

I'm experiencing an issue when passing a url like a youtube video link, as soon as the audio starts to playing I get firefox crash screen.

wondering if you guys have any insight around that ?

I'm creating a localhost service based on your recording mechanism.

Thanks
-Oliver

**Comment by aburnson** [comment]
Try to see if you can find and capture the Crash Report out of the `/tmp/foo4` [profile directory](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/71fdc7cc0f118d8ca89b765ac8531123137fe241/recording/run.sh#L28) to see what may be causing the tab crash. Given that it occurs when you try to play a video, it's possible that there is a codec setting that may need to be either enabled or disabled.

**Comment by OliverwengFiltered** [comment]
found the crash report but it's not encoded with utf-8 strings. the file name is `/tmp/recorder/crashes/store.json.mozlz4`
I changed the user name from foo4 to recorder in run.sh file, that's why it's under /tmp/recorder.

based on my observation, it's fine when playing a video muted, but when playing a video unmuted, it will crash consistently. assuming it's audio encoding issue ?

weird that if use aws ec2 ecs , the recording with audio seems fine.

however, if local host based on the recording folder,  it doesn't seem to work with audio. 

PFA for an example recorded mp4 file.
https://ucarecdn.com/601f3fae-d7a8-4246-adf9-5dc05a83ac20/1.mp4

**Comment by aburnson** [comment]
Thanks @OliverwengFiltered. Would it be possible to retrieve the crash report file and attach to this issue? From the extension, it looks to be encoded in a Mozilla-specific `mozlz4` encoding, but there are publicly available tools for decompressing files in this encoding.

**Comment by OliverwengFiltered** [comment]
here is the decoded crash report json:
https://ucarecdn.com/a1299250-af83-42ae-aa2c-8f2d0b31f0b5/search_extracted.json

**Comment by aburnson** [comment]
Based on that crash report, it appears the main thread in Firefox is crashing, potentially when it tries to [load OpenH264](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/run.sh#L44) for playing the video. We will try to reproduce this and see what can be done about this.

**Comment by OliverwengFiltered** [comment]
Hi @aburnson ,

thank you for the support.

and not sure if it helps to reproduce but here is what I have done to reproduce it on my local consistently.
1. get recording folder and Dockerfile from master branch.
3. use `docker image build` to build local image.
4. use docker run to run the image and attach to shell command.
5.  in shell command run run.sh like this: `./run.sh https://www.youtube.com/watch?v=lgUDuZS9MVQ bucketName` (run.sh has been slightly modified to support run with args)
6. after recording for like 10 seconds, stop recording by executing `kill pid`
7. watch recorded video, it will show firefox crash.

I'm using mac os latest version. same Dockerfile from ubuntu:18.04

**Comment by aburnson** [comment]
Thanks for the repro steps, @OliverwengFiltered. That is helpful.

**Comment by OliverwengFiltered** [comment]
Hi @aburnson 

Wondering if there is any updates about this one ?

Thanks.
-Oliver

**Comment by ziyiz-amzn** [comment]
@OliverwengFiltered For ECS, we have [this configuration](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/pull/17) to stop the FF tab from crashing. I guess the same config should be considered if running the docker on localhost machine. 

Meanwhile, we are trying to reproduce the issue without running on ECS.

**Comment by ziyiz-amzn** [comment]
Tried to reproduce the issue by running the recording docker container both on a local Mac and a cloud9 instance against the URL https://www.youtube.com/watch?v=lgUDuZS9MVQ.

No crash was observed during ~10 tests.

If you are still having this issue, you can try to explicitly specify --shm-size parameter in `docker run` command. [For example](https://github.com/aws-samples/amazon-chime-meeting-broadcast-demo/blob/master/Makefile#L13). We have applied the [SharedMemorySize parameter](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L164-L165) to ECS task definition in this demo, rather than in the running time of docker container.

It may explain the reason why the recording in ECS is fine which you mentioned above. 

Hope it helps.

**Comment by OliverwengFiltered** [comment]
yup, it might be just a firefox v78 issue, never seen that again after using v83. please close this one now. thank you.
