### ISSUE TITLE
stop recording api is not returning recorded video name or url

### ISSUE THREAD

**Issue by rohit0337** [aws-samples/amazon-chime-sdk-recording-demo#30]
hello
when i call stop recording api its returns me json data but in this json data there no details of recorded video stored path.
how to achieve it.

**Comment by anuranduttaroy** [comment]
@rohit0337 You can find the recording in an S3 bucket named `chime-meeting-sdk-<aws-account-id>-<region>-recordings`. E.g. `chime-meeting-sdk-1234567890-us-east-1-recordings`

This is pointed out in the README section [**Stop the recording and view the recording artifact**](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#stop-the-recording-and-view-the-recording-artifact) *point number 2*

```
Once the recording stops, open the AWS Console and navigate to Amazon S3. You will find a recording in the bucket chime-meeting-sdk-<aws-account-id>-<region>-recordings, with a key name YYYY/MM/DD/HH/.mp4.
```

**Comment by ankit-maheshwari** [comment]
Hi @anuranduttaroy we are implementing the recording feature and wants the saved recording location/ name to save against the meeting in our own database. Hence the meeting attendees can access the recording from our portal.

**Comment by rohit0337** [comment]
hi @anuranduttaroy   we are implementing the recording feature and wants the saved recording location/ name to save against the meeting in our own database. Hence the meeting attendees can access the recording from our portal. 
so how can we achieve recording video path in the stop recording api response
