### ISSUE TITLE
@rohit0337 You can find the recording in an S3 bucket named `chime-meeting-sdk-<aws-account-id>-<region>-recordings`. E.g. `chime-meeting-sdk-1234567890-us-east-1-recordings`

### ISSUE THREAD

**Issue by rohit0337** [aws-samples/amazon-chime-sdk-recording-demo#33]
@rohit0337 You can find the recording in an S3 bucket named `chime-meeting-sdk-<aws-account-id>-<region>-recordings`. E.g. `chime-meeting-sdk-1234567890-us-east-1-recordings`

This is pointed out in the README section [**Stop the recording and view the recording artifact**](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#stop-the-recording-and-view-the-recording-artifact) *point number 2*

```
Once the recording stops, open the AWS Console and navigate to Amazon S3. You will find a recording in the bucket chime-meeting-sdk-<aws-account-id>-<region>-recordings, with a key name YYYY/MM/DD/HH/.mp4.
```

_Originally posted by @anuranduttaroy in https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/30#issuecomment-663301030_

**Comment by rohit0337** [comment]
hi  
we are implementing the recording feature and wants the saved recording location/ name to save against the meeting in our own database. Hence the meeting attendees can access the recording from our portal.
so how can we achieve recorded video s3 name and path in the response of "stop recording api"

**Comment by anuranduttaroy** [comment]
Here are the steps we are following related to storing the meeting recording.
1. We are creating the `Recording Artifacts S3 Bucket` here : https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L74-L79. 
2. Passing this bucket name as an environment variable to the lambda function here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L120
3. The lambda reads the bucket name from the environment variable here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L13
4. It then passes the bucket name to the ECS Task as part of container overrides here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L105
5. That variable is received here in run.sh: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/run.sh#L14
6. It uses that variable to pass it on to record.js which does the media capture & storing it to s3: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/run.sh#L69
7. That is being used to initialize the s3 uploader here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L77

As you can see, we need to pass it on to the recorder while starting it. If the bucket name is static, you can store it somewhere and return it as part of the `stop recording` API call which is constructed here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L147-L154

Currently, the `stop recording` API just stops the ECS Task and returns the response it gets from that.

If you have feedback or feature requests, you can get in touch with us through the [AWS Customer Support portal](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html).

Let me know if this helps. Feel free to re-open this issue if you have further questions about this.

**Comment by rohit0337** [comment]
hello @anuranduttaroy  where i find these run.sh and record.js in aws console . i know these files are avialable in recording demo of git, but in aws lamda function i am only able to see index.js file
