### ISSUE TITLE
Recording overview

### ISSUE THREAD

**Issue by krokhale** [aws-samples/amazon-chime-sdk-recording-demo#36]
- Have looked through all the docs.
- I have also deployed the stack/ecr etc according to the docs.
- Deployed the server less demo as well.

From what I understand, the recording code is basically a hack/bot that NEEDS to know the public URL of meeting that is taking place. The Bot then visits the page as an attendee and records the page.

What if the meeting is behind a user name password authentication on a private server? What If I don't want to use server less demo? What If i just want to use the AWS SDK for recording?

Is that even possible right now?

**Comment by Aeramor** [comment]
It is possible; I've got it working on private server with authenticated meeting. (It does require a lot of work though)

**Comment by vidya-mohan** [comment]
@krokhale - thanks for the interest in the demo app. The current demo does require a public URL of the meeting so the bot can join. You can enhance it with what ever customization you wish
