### ISSUE TITLE
Audio/video out of sync

### ISSUE THREAD

**Issue by colohr** [aws-samples/amazon-chime-sdk-recording-demo#38]
Recording results in video/audio out of sync.  This does not happen when actively connected via the web app. 

Ive noticed several times the audio (up to a min) is missing from the beginning of the video.

Any info/direction appreciated.

**Comment by Aeramor** [comment]
In record.js there is a bit where it attempts to sync the audio/video. After some testing I ended up with `'adelay=delays=250|250',` which works pretty well (the default is 1000|1000).

**Comment by anuranduttaroy** [comment]
@colohr you can change the values of `adelay` here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L52-L53 to see if that helps.

**Comment by anuranduttaroy** [comment]
Feel free to re-open if it's still an issue.

**Comment by junedlanja** [comment]
In my case Im not getting audio at all
