### ISSUE TITLE
In order to use the capacity provider, no launchType should be specified when calling runTask

### ISSUE THREAD

**Issue by johanderuijter** [aws-samples/amazon-chime-sdk-recording-demo#40]
The capacity provider created by the deploy script isn't actually used when specifying a launchType when calling runTask. To use the created capacity providers, the launchType should be dropped from the parameters as that will cause the default (and in this case only) capacity provider to be used.

https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/db5b082800320df0d52531a1ca3dc3b22c5bb4c0/src/index.js#L93

I do believe that not providing a launchType means there HAS to be a capacity provider present, so i am not sure that is the way to go for this demo or whether this behaviour should simply be documented.

**Comment by tenge-amzn** [comment]
Chime SDK team has launched a new service to provide meeting capture capabilities with original video resolution and frame rate. You will not need to provision your own container infrastructure. Instead, just call the API from AWS SDK and provide a prepared S3 bucket to receive the artifacts. 

To know more, please check out the blog:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
