### ISSUE TITLE
Chinese or Japanese show Garbled code in video

### ISSUE THREAD

**Issue by wesigi** [aws-samples/amazon-chime-sdk-recording-demo#43]
When metting page has chinese or japanese. It can't be display in the record. Like chat message.
![issue](https://user-images.githubusercontent.com/44694427/93414279-887e7c00-f8d3-11ea-86f0-e0aba282246b.png)

**Comment by anuranduttaroy** [comment]
This looks like a browser issue. I could find some articles about East Asian language support like these ones 
- https://support.mozilla.org/en-US/questions/960381
- https://support.mozilla.org/en-US/questions/970836

It sounds like some additional support packages needs to be installed for Firefox to support CJK fonts. I could find some related articles on the internet which shows how to install those fonts on Linux. Here are some of them
- https://tex.stackexchange.com/questions/125843/how-to-install-cjk-font-to-ubuntu-latex
- https://kbpdfstudio.qoppa.com/how-to-install-cjk-fonts-on-linux/
- https://zoomadmin.com/HowToInstall/UbuntuPackage/fonts-noto-cjk

You will probably have to add the additional packages in the below mentioned line where we install required packages like `nodejs`, `pulseaudio`, `xvfb`, `firefox`, `ffmpeg`, `xdotool` & `unzip`.

https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/Dockerfile#L13

**Comment by wesigi** [comment]
@anuranduttaroy 
Thanks it works。
add the package fonts-noto-cjk in the Dockerfile.
