### ISSUE TITLE
For Recording I have meeting Id ,how to know the meeting URL.

### ISSUE THREAD

**Issue by sidharth-sid** [aws-samples/amazon-chime-sdk-recording-demo#45]
I have integrated the AWS chime to my application, but I'm facing difficulty in the recording where it requires the meeting URL to record. The meeting is inside the same client application but we don't open the meeting in a separate window.
So how do we construct the meeting URL fr recording, we have the meeting Id.
@anuranduttaroy @aburnson @vidya-mohan

**Comment by sidharth-sid** [comment]
We have a web application where we use the AWS chime meeting (SDK). So each logged in user in the application will be able to create or join a chime meeting. We were able to use the chime SDK and users were able to create and join calls.
As part of the chime integration to our App, we also needed to record the calls happening in the application.
so we were planning to use the recording feature supported by AWS (https://github.com/aws-samples/amazon-chime-sdk-recording-demo).

The problem we encountered is for demo chime meeting they have an meeting URL like "https://XXXXX.execute-api.xxxx.amazonaws.com/Prod/v2/" which the recording App uses for recording the screen and audio/video. But in our application we don't open the meeting in a separate window, we show the meeting in the current chat window that's already existing. So we don't have a meeting URL kind of thing , only meeting Id is available.(using which attendee joins)

Also the meeting happens behind the login authentication so i went through the recording system and found that the recording App tries to open the meeting in a Firefox and records their screen. This won't be possible as we don't have a meeting URL which directs to an ongoing meeting and also we have Application login authorization which is required.

So we needed immediate support to resolve the recording issue we face now.

**Comment by NelsonMeleth** [comment]
Facing same situation here. Documentation only available for serverless meetings. Did you find any solution?

**Comment by ziyiz-amzn** [comment]
In this implementation, the recording agent has to join a meeting as an separate attendee via URL and bypass authentication. 
In the demo, https://XXXXX.execute-api.xxxx.amazonaws.com/Prod/v2/ is a portal which bypass authentication or permission popup window, which meeting is created from Chime SDK [demo](https://github.com/aws/amazon-chime-sdk-js).

**Comment by anuranduttaroy** [comment]
Thank you for your interest in the SDK. The current Amazon Chime SDK does not support meeting recording out of the box. Read more here: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#does-amazon-chime-sdk-support-recording-functionality

The current recording demo is setup to record a webpage - our demo application [bypasses authentication](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L255-L263) to let the bot into the meeting. To support your specific use-case, you can modify our solution with your requirements.
