### ISSUE TITLE
Multi-stream recording

### ISSUE THREAD

**Issue by m-minasyan** [aws-samples/amazon-chime-sdk-recording-demo#46]
Good afternoon. I need to be able to record multiple Chime streams at the same time. How can all this be done?

**Comment by vidya-mohan** [comment]
@m-minasyan could you help us understand what did you mean by multiple Chime streams? Did you mean multiple meetings? Or separate audio and video streams in the same meeting?

**Comment by m-minasyan** [comment]
> @m-minasyan could you help us understand what did you mean by multiple Chime streams? Did you mean multiple meetings? Or separate audio and video streams in the same meeting?

I mean to record multiple meetings in the same time.

**Comment by ziyiz-amzn** [comment]
You can use the deployed recording URL to start recording multiple meetings. 

You can scale by setting the ECS auto scaling group [here](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L32-L40). 

Hope it helps.

**Comment by marloncard** [comment]
There's a bit of a delay with the current auto scaling group configuration and being able to handle a second recording. A second instance comes online about 10 minutes after I start a recording. That provides enough cpu to start a second recording. From then on there's more than enough instances online for additional recordings. In case anyone is having trouble with this.

**Comment by anuranduttaroy** [comment]
The 2nd point in the [FAQ](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#faq) talks about ways to speed up the bot join process. I have also mentioned way to speed up the bot join and optimize the use of EC2 instance here in this comment https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/81#issuecomment-837202885

Hope this helps.

Feel free to re-open this in case you have more questions.
