### ISSUE TITLE
Error creating Image

### ISSUE THREAD

**Issue by tumbelin** [aws-samples/amazon-chime-sdk-recording-demo#48]
Hi, I couldn't  follow all the Walkthrough with Cloud9 always getting this error:
"Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2200.30: no space left on device
Makefile:17: recipe for target 'build_upload' failed" 

How can this be fixed?

Also, I am using the setup recommended for Cloud9
![Capture](https://user-images.githubusercontent.com/26089996/95417778-7f456580-08fb-11eb-9fd6-d011b2857a12.PNG)

**Comment by tumbelin** [comment]
@anuranduttaroy

**Comment by ehickey08** [comment]
@tumbelin I was running into a similar issue. I used the resize.sh file from the aws docs (https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html) before running any of the commands and it worked fine for me. I was on an Amazon Linux platform though.

**Comment by tumbelin** [comment]
@ehickey08 thanks a lot, I finally could continue the walkthrough

**Comment by JesusCamaRay** [comment]
How much GiB is required for the image?

**Comment by tumbelin** [comment]
Hola @JesusCamaRay , la verdad no sé, como era un ambiente temporal en CLoud9 use el máximo que era 20, y una vez tuve la imagen lo elimine para no generar mucho sobre costos
