### ISSUE TITLE
failed during deploy step

### ISSUE THREAD

**Issue by Rushabh98** [aws-samples/amazon-chime-sdk-recording-demo#49]
Command sam failed with exit code 1 signal null
Error: Failed to create/update the stack: rushabh-recording-stack, Waiter StackCreateComplete failed: Waiter encountered a terminal failure state

![image](https://user-images.githubusercontent.com/62867056/96573570-f9a6ba00-12eb-11eb-9ec2-5c528c419279.png)

**Comment by ttlpta** [comment]
@Rushabh98 Did you resolve this issue? I have met this too

**Comment by moracarlos** [comment]
In my case, I was using a bucket created in a different region than specified. Check if it's your case @ttlpta @Rushabh98

**Comment by ttlpta** [comment]
I forgot to add the policy AdministratorAccess for my user. 
Btw, Do you meet this error @moracarlos 
![image](https://user-images.githubusercontent.com/9917124/96948850-b9745100-1510-11eb-8a2f-e9a47fc7bd0c.png)

**Comment by anuranduttaroy** [comment]
@ttlpta we store the name of the `autoScalingGroupCapacityProviderName` here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/deploy.js#L157 and use that name to create the ECS Capacity Provider here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/deploy.js#L178

Could you print out the variable `autoScalingGroupCapacityProviderName` somewhere before this line https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/deploy.js#L178 and tell me what that is?

**Comment by ttlpta** [comment]
Thank @anuranduttaroy for the reply. I found the reason is I named the stack with the prefix aws-*** . I changed to re-run the command but still meet another issue which is not related to the naming :(

**Comment by anuranduttaroy** [comment]
What's the new issue you are seeing?

**Comment by ttlpta** [comment]
@anuranduttaroy  I met this #52

**Comment by anuranduttaroy** [comment]
@Rushabh98 are you still seeing this issue?

**Comment by junedlanja** [comment]
@anuranduttaroy facing issue #52

**Comment by anuranduttaroy** [comment]
@junedlanja it seems https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/52 was solved by @ttlpta https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/52#issuecomment-730411198

Closing this one. @Rushabh98 feel free to re-open if this is still an issue for you.
