### ISSUE TITLE
Can I use AWS CLI instead of Cloud 9 to deploy this app?

### ISSUE THREAD

**Issue by ttlpta** [aws-samples/amazon-chime-sdk-recording-demo#50]
Can I use AWS CLI instead of Cloud 9 to deploy this app?

**Comment by anuranduttaroy** [comment]
Yes, you can use AWS CLI or deploy it from you local environment with the required AWS Credentials setup to do this as well. We just recommend Cloud 9 since it's in the same AWS account and it makes the setup simple.

**Comment by anuranduttaroy** [comment]
Feel free to re-open if it does not work for you.
