### ISSUE TITLE
Cannot read property 'Instances' of undefined

### ISSUE THREAD

**Issue by ttlpta** [aws-samples/amazon-chime-sdk-recording-demo#52]
![image](https://user-images.githubusercontent.com/9917124/96972309-8d70c400-1540-11eb-8d7b-a28a5bc2268c.png)

**Comment by junedlanja** [comment]
@ttlpta Facing similar issue. Do you found solution?

**Comment by ttlpta** [comment]
@junedlanja  yes, in my case, I grant the wrong role for the user. It is not admin

**Comment by anuranduttaroy** [comment]
@junedlanja did this solve your issue?

**Comment by junedlanja** [comment]
@anuranduttaroy Yes in my case docker image uri (`my-docker-image-uri`) region and `region` were different in .`node ./deploy.js -b <my-bucket> -s <my-stack> -i <my-docker-image-uri> -r <region>`. Deployed on same region and it successfully deployed.
