### ISSUE TITLE
CannotPullContainerError: Error response from daemon: pull access denied for my-docker-image

### ISSUE THREAD

**Issue by dsuraj72** [aws-samples/amazon-chime-sdk-recording-demo#55]
Hi Team,

I'm getting following error. Whenever i execute the API G/W with start action, i'm getting following error under Task --> Container --> Status Reason & the task status changes to STOPPED.

**CannotPullContainerError: Error response from daemon: pull access denied for my-docker-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied**

I've integrated the browser demo Chime SDK in React app & have made required provision for Recorder-Bot as attendee in the meeting. I'm testing the recording feature locally & passing the following URL in POST call with URL encoded.

http://localhost:3000/meeting?m=12345&record=true

Pls let me know if you need any more details.

Thanks.

**Comment by dsuraj72** [comment]
@anuranduttaroy can you help me with this issue?

**Comment by cavinpabua** [comment]
hi @dsuraj72 
I am having the same issue. Even just using the Demo template provided. 
Did you ever solved on your side?
