### ISSUE TITLE
Can I use the free tier instance to run demo?

### ISSUE THREAD

**Issue by ttlpta** [aws-samples/amazon-chime-sdk-recording-demo#56]
In the demo, it requires only these instances and they are not free. Can I add the free instance type "Micro" for this?
- mt2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.large
    - t3.xlarge
    - t3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.8xlarge
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge

**Comment by anuranduttaroy** [comment]
Yeah you can add any instance there. The only thing to keep in mind is that the `ffmpeg` process for extracting media is a bit resource intensive. So sometimes, if you are using a `Micro` instance, it would not have the best quality. But you can try out and see how that works out for you.

**Comment by ttlpta** [comment]
Thank you for your replies @anuranduttaroy . I will try
