### ISSUE TITLE
Meeting Recorder doesn't appear

### ISSUE THREAD

**Issue by moracarlos** [aws-samples/amazon-chime-sdk-recording-demo#57]
The meeting recorder doesn't join the meeting. The recorded video stays:

<img width="1270" alt="Captura de Pantalla 2020-11-02 a la(s) 10 45 38 a  m" src="https://user-images.githubusercontent.com/8855487/97881440-c9521900-1cf8-11eb-9af3-9d615b7bed6c.png">

**Comment by anuranduttaroy** [comment]
What is the URL that you are passing to the recorder? Is it the V2 link as mentioned here in [Point #3](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#start-an-amazon-chime-sdk-meeting-with-our-serverless-demo-and-join-with-multiple-participants)

**Example**: If the meeting URL is `https://abcdefghij.execute-api.us-east-1.amazonaws.com/Prod/v2?m=MyMeetingTest`, then the encoded URL which needs to be passed to the meeting recorder should look like `https%3A%2F%2Fabcdefghij.execute-api.us-east-1.amazonaws.com%2FProd%2Fv2%3Fm%3DMyMeetingTest`

**Comment by anuranduttaroy** [comment]
@moracarlos feel free to re-open if it's still an issue.
