### ISSUE TITLE
No Recording created in S3

### ISSUE THREAD

**Issue by tumbelin** [aws-samples/amazon-chime-sdk-recording-demo#58]
Hi, I have a big issue I noticed sometimes the video is not storage in S3, what I usually do is:  after calling the API with action "start" it returns a regular taskId (arn:aws:......), I storage that info in my database and when the user wants to stop it, he calls the action "stop", everything goes well so far, when the time comes I call the action "stop" and what I expect is to have the video object in S3, but sometimes there is not file and I didn't get any error from calling the API when I am trying to stop it, so why could this happened and how can be solved?

I'm really worried because this recording feature is already in production and I say to the customer it is recording, when sometimes it probably doesn't

What I think is it could be related to concurrent recording meeting and the autoscaling instances for each recording

**Comment by anuranduttaroy** [comment]
@tumbelin can you attach the logs from the ECS task when this issue happens?

**Comment by tumbelin** [comment]
No, sadly I didn't get the ECS Task. Do you think it is possible that I get the right ECS task for the start action, also for stop and in the end don't get any recording?

**Comment by anuranduttaroy** [comment]
Once you start the recording, you would get an ECS task ARN back in the response. That task would be seen in the ECS console. If the task ends, there is a section in ECS to get logs for the "Stopped" tasks as well. Could you check if the logs are present there?

<img width="868" alt="Screen Shot 2020-12-16 at 2 39 57 PM" src="https://user-images.githubusercontent.com/4708896/102415283-c7909c00-3fac-11eb-9830-0d236f37803e.png">

**Comment by anuranduttaroy** [comment]
Hey @tumbelin, feel free to re-open this if you are still experiencing this issue.
