### ISSUE TITLE
Handle Names

### ISSUE THREAD

**Issue by gerardovs76** [aws-samples/amazon-chime-sdk-recording-demo#63]
Hi, thanks for your project.

I have a question. What if I want to handle a custom name. I don't want that date/time name.

Or how can I have a reference to the mp4 object in S3.

If I have hundreds of recordings, how can I reference each one without going to S3 bucket and manually check one by one.

I've already tried modifying the index.js file. Passing a meetingId as environment parameter and then in recording.js use that name to upload the file to S3. But, I can see there is no name changed. 

Index.js
`
function startRecording(event, context, callback, meetingUrl, meetingId) {
    let ecsRunTaskParams = {
        cluster: ecsClusterArn,
        launchType: "EC2",
        count: 1,
        overrides: {
            containerOverrides: [ 
                 { 
                    environment: [ 
                        { 
                            name: "MEETING_URL",
                            value: meetingUrl
                        },
                        {
                            name: "RECORDING_ARTIFACTS_BUCKET",
                            value: recordingArtifactsBucket
                        },
                        {
                            name: "FILE_NAME",
                            value: meetingId
                        }
                    ],
                    name: ecsContainerName
                }
            ],
        },
        placementConstraints: [{
            type: "distinctInstance"
        }],
        taskDefinition: ecsTaskDefinationArn
    };
    
    ecs.runTask(ecsRunTaskParams, function(err, data) {
        if (err) {
            console.log(err);   // an error occurred
            response.statusCode = err.statusCode;
            response.body = JSON.stringify(err, null, ' ');
            context.succeed(response);
        }
        else {
            console.log(data);  // successful response
            response.statusCode = 200;
            response.body = JSON.stringify((data.tasks.length && data.tasks[0].taskArn) ? data.tasks[0].taskArn : data, null, ' ');
            context.succeed(response);
        }
    });
}
`

record.js

`
const NEW_FILE_NAME = process.env.FILE_NAME;
------

const fileName = `${year}/${month}/${day}/${hour}/test${NEW_FILE_NAME}.mp4`;

------

new S3Uploader(BUCKET_NAME, fileName).uploadStream(transcodeStreamToOutput.stdout);
`

**Comment by ziyiz-amzn** [comment]
Your approach seems very close to it. 

Have you added the `meetingId` parameter when you call `startRecording()` in [lambda handler](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/f40d3b84db9940bcf7af206b3a532b5e634788b8/src/index.js#L40-L44)?

**Comment by vidya-mohan** [comment]
Resolving as no response
