### ISSUE TITLE
Deployment fails at step 3 (make ecr)

### ISSUE THREAD

**Issue by schuettc** [aws-samples/amazon-chime-sdk-recording-demo#64]
During deployment using Cloud9 m5.large:

 /tmp/apt-dpkg-install-aZaNrP/194-firefox_84.0.2+build1-0ubuntu0.18.04.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c /usr/bin/apt-get update &&      /usr/bin/apt-get install -y curl &&     curl -sL https://deb.nodesource.com/setup_10.x | bash - &&      /usr/bin/apt-get update &&      /usr/bin/apt-get upgrade -y &&  /usr/bin/apt-get install -y nodejs pulseaudio xvfb firefox ffmpeg xdotool unzip' returned a non-zero code: 100
Makefile:17: recipe for target 'build_upload' failed
make: *** [build_upload] Error 100
xxxxxxxxxxxx:~/environment/amazon-chime-sdk-recording-demo (master) $ df -ah
Filesystem      Size  Used Avail Use% Mounted on
sysfs              0     0     0    - /sys
proc               0     0     0    - /proc
udev            3.8G     0  3.8G   0% /dev
devpts             0     0     0    - /dev/pts
tmpfs           776M  784K  775M   1% /run
/dev/nvme0n1p1  9.7G  9.4G  235M  98% /

------------

Increasing size of Cloud9 instance volume in EC2 resolves:

Image URI in ECR repository: xxxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/chime-recording:latest
xxxxxxxxxxxxx:~/environment/amazon-chime-sdk-recording-demo (master) $ df -ah
Filesystem      Size  Used Avail Use% Mounted on
sysfs              0     0     0    - /sys
proc               0     0     0    - /proc
udev            3.8G     0  3.8G   0% /dev
devpts             0     0     0    - /dev/pts
tmpfs           776M  768K  775M   1% /run
/dev/nvme0n1p1   20G   11G  9.1G  53% /

**Comment by anuranduttaroy** [comment]
Hey @schuettc, 

I tried to deploy the recording application on a cloud9 instance running on `c4.4xlarge` instance. My deployment failed too. But then the issue was there were some unwanted docker images which was cached. Try to remove the cached docker images using the command `docker image prune -a` and try to run the make command again i.e `make ECR_REPO_URI=<repositoryUri>`

Let me know if this works.

**Comment by schuettc** [comment]
Thanks, that did help.   Thanks for updating the FAQ with that as well.
