### ISSUE TITLE
Recording bot is not joining

### ISSUE THREAD

**Issue by TrierHealth** [aws-samples/amazon-chime-sdk-recording-demo#65]
Hi,

Recording bot is not joining. The entire setup was fine.
I see in the ECS logs the below message:
(firefox:62): LIBDBUSMENU-GLIB-WARNING **: 15:02:21.586: Unable to get session bus: Failed to execute child process ?dbus-launch? (No such file or directory)
Could someone help?

Thanks,
Ravi.

_Originally posted by @nagydniel in https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/16#issuecomment-638658340_

**Comment by TrierHealth** [comment]
The above warning is gone after installing: dbus-x11
But still the bot is not joining.

**Comment by TrierHealth** [comment]
Adding /v2 in the meeting url fixed the issue. Bot is joining now.

**Comment by thinhlx1993** [comment]
> Adding /v2 in the meeting url fixed the issue. Bot is joining now.

I don't know how to add /v2 to the meeting URL. Can you help me? I have trouble when recording video. The recoding video always show can't connected to the server at <metting_id>?record=true

**Comment by TrierHealth** [comment]
Hi @thinhlx1993 , if your meeting url is
https://UNIQUE.execute-api.us-east-1.amazonaws.com/Prod/
Just add v2/ at the end making it
https://UNIQUE.execute-api.us-east-1.amazonaws.com/Prod/v2/

Thanks,
Ravi.
