### ISSUE TITLE
Cannot record website that is outside of AWS

### ISSUE THREAD

**Issue by gilles-leblanc** [aws-samples/amazon-chime-sdk-recording-demo#69]
We have deployed and tested the demo application and we can record just fine. 

We already have an existing web site that uses Chime to which we want to add recording. The application isn't deployed on AWS but on a third party server but it calls the Chime SDK.

When we try to record this URL or any external URL (we have tried for example our company's website) we get a video that contains a Firefox window with the following message:

<img width="1402" alt="Capture d’écran, le 2021-01-25 à 13 50 31" src="https://user-images.githubusercontent.com/712010/105751864-9349bd00-5f14-11eb-94e3-6006b5440cbe.png">

Is this an issue with our EC2 configuration or is it only possible to record something that is hosted on AWS like in the demo application?

**Comment by jpfortin** [comment]
As shown in the image, it turned out that the SDK needs to record a URL that absolutely has a query string. The SDK could handle both cases preferably.

run.sh line 8
`BROWSER_URL="${MEETING_URL}&record=true"
`
