### ISSUE TITLE
Audio & video no synced 

### ISSUE THREAD

**Issue by ellismarte** [aws-samples/amazon-chime-sdk-recording-demo#71]
Hey I noticed that my audio and video are off by a second or two. I noticed there's a settting in record.js

https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L53

Should I adjust this to get rid of they delay? If so what would the values be? It seems the audio is ahead of the video.

**Comment by michhyun1** [comment]
Hey @ellismarte, I just posted a response to your duplicate issue on the JK SDK repo, but just to re-iterate, please refer to this issue regarding this topic -https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues?q=is%3Aissue+-label%3ATriaged+is%3Aclosed

**Comment by anuranduttaroy** [comment]
@ellismarte here is the solution that worked for others https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/38#issuecomment-685148540.

Could you give this a shot and let us know if that works for you?

**Comment by ellismarte** [comment]
Thanks. I'll try to reduce the delay. I just posted another issue that has to do with movflag -- if you guys have a minute I'd appreciate your feedback.

**Comment by anuranduttaroy** [comment]
Closing this since the original issue was addressed.
