### ISSUE TITLE
Question : Can we increase Screen Share video recording quality 

### ISSUE THREAD

**Issue by vinciabhinav** [aws-samples/amazon-chime-sdk-recording-demo#72]
Hey Team, Thanks for this awesome resource !

Issue Context: I am using react aws chime ContentShare Component. [The share quality in the meeting is quite good ], but the recording quality in s3 is relatively low. 

Attached screenshots : 

Live Screenshare quality: 
<img width="826" alt="Capture (3)" src="https://user-images.githubusercontent.com/53426516/108813847-c5b00e00-75d7-11eb-9274-873d5fd6d496.PNG">

Recoding Screenshare quality:  

![image](https://user-images.githubusercontent.com/53426516/108813760-9e594100-75d7-11eb-91b4-0cca54563e17.png)

I have tried 
1. changing bitrate to 5k/6k, 
2. setting min-max range for bitrate [3-6k]
3. Increased frame rate to 60 
4.  '-pix_fmt', 'yuv444p',
5.  Changed preset : '-preset', 'ultrafast',
6.  Changed to lossless compression : '-qp', '0',

PS: Internet Connectivity is good

**Comment by brunokunace** [comment]
@vinciabhinav you solve this?

**Comment by vinciabhinav** [comment]
Yes, 
In recording/run.sh file

Change 

-SCREEN_WIDTH=${RECORDING_SCREEN_WIDTH:-'1280'}
-SCREEN_HEIGHT=${RECORDING_SCREEN_HEIGHT:-'720'}

to below

+SCREEN_WIDTH=${RECORDING_SCREEN_WIDTH:-'1920'}
+SCREEN_HEIGHT=${RECORDING_SCREEN_HEIGHT:-'1080'}

**Comment by tenge-amzn** [comment]
Chime SDK team has launched a new service to provide meeting capture capabilities with original video resolution and frame rate. You will not need to provision your own container infrastructure. Instead, just call the API from AWS SDK and provide a prepared S3 bucket to receive the artifacts. 

To know more, please check out the blog:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
