### ISSUE TITLE
Movflags

### ISSUE THREAD

**Issue by ellismarte** [aws-samples/amazon-chime-sdk-recording-demo#73]
Hey I noticed that when I stream my recording it takes a while to start. I'm thinking adding this flag "-movflags faststart" should speed up the start of the video but I noticed this comment and was wondering if this means i can't add faststart?

https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L59-L60

**Comment by anuranduttaroy** [comment]
Hey @ellismarte, I added a [FAQ](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#faq) which talks about some of the ways to speed up the bot join process. 

Also, here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/81#issuecomment-837202885 I mentioned how we can use Amazon ECS to use different placement constraints and strategies which can also help pack multiple recordings in a single instance and also speed up the bot join time. 

Hope this helps.

**Comment by jing-chen1** [comment]
Closing the issue for now. Feel free to reopen it if you still have problems.
