### ISSUE TITLE
Simple hack: what if users closed the tab instead of pressing the end call button.

### ISSUE THREAD

**Issue by adesun2k** [aws-samples/amazon-chime-sdk-recording-demo#76]
In some cases the users may close the tab instead of hitting the end button. In this case will the recording ever stop at any point or the recording is gone into oblivion?.

**Comment by anuranduttaroy** [comment]
Hey @adesun2k

The only time in this demo the recording stops is when we call the stop recording API. So if you want to handle the situation you mentioned, the bot needs to be intelligent to stop recording when the meeting ends. 

If there are no participants in the meeting, the Meeting AutoEnd policies would kick in and the meeting will end. Something you can do to handle that is, whenever you get a `meetingEnded` event for you meeting (Read more here: https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html), your code can call StopRecording API which would end the recording. 

Let me know if this answers your question.

**Comment by anuranduttaroy** [comment]
@adesun2k please feel free to re-open this issue if you still have question about this.
