### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by shubhamgoswamiofficial** [aws-samples/amazon-chime-sdk-recording-demo#79]
Can we get what all permissions are required by our IAM user to perform all the stack tasks. It's hard to execute every time and new permission is required. Any one who can help?

**Comment by michhyun1** [comment]
Hi @shubhamgoswamiofficial  - In the README, a prerequisite is to have an IAM Role with the AdministratorAccess policy attached. Let me know if you have any other questions.
