### ISSUE TITLE
Unable to pass input screen during recording.

### ISSUE THREAD

**Issue by Joypaul11** [aws-samples/amazon-chime-sdk-recording-demo#8]
Followed all steps, but the recording bot is stuck in the input screen 

![image](https://user-images.githubusercontent.com/15178510/79865238-7964d200-83f8-11ea-8399-0f1c20d4213b.png)

Is it not possible for the bot to directly go to the meeting screen ?

**Comment by cmdavinder** [comment]
Having same problem.

**Comment by cmdavinder** [comment]
by the way, I got things working earlier when I had the setup in us-east-1. However, the bot is unable to get past the login page when I ran did the setup in us-east-2.

**Comment by lzblue** [comment]
Hi, I realized you need to use v2 to make this work:

<demo url>/Prod/**v2**?m=<meeting number>

**Comment by nilaydave38** [comment]
I had same issue even audio also not recorded.

Anyone facing an audio recording issue as well?
