### ISSUE TITLE
MP4 file generated is not editable by Quick Time Player on Mac

### ISSUE THREAD

**Issue by MohammedAbadi1991** [aws-samples/amazon-chime-sdk-recording-demo#84]
Download the generated mp4 file from S3 bucket.
Open it using Quick Time Player on Mac.
The file is not editable (Trim option is disabled)
I was able to edit it on Windows using Active presenter.

**Comment by tenge-amzn** [comment]
Chime SDK team has launched a new service to provide meeting capture capabilities with original video resolution and frame rate. You will not need to provision your own container infrastructure. Instead, just call the API from AWS SDK and provide a prepared S3 bucket to receive the artifacts. 

To know more, please check out the blog:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

**Comment by MohammedAbadi1991** [comment]
Thanks a lot for your response, we will test it.
