### ISSUE TITLE
Black screen on video section of customer camera on the recorded video

### ISSUE THREAD

**Issue by robertbarron** [aws-samples/amazon-chime-sdk-recording-demo#88]
Hello,

We recently started to see an issue where the section where the customers' camera is viewed is black. We had seen this problem before but it was very rare. Currently, we are watching it 1 or 2 times for every 10 recordings.

While having the call, the section where the customer's camera is being viewed looks great, but the recorded video shows those section with the gray background.

The relevant changes of the code was to remove the "placement" property from the lambda, but after seeing this error we roll it back, but the problem still persist.

Has anyone had a similar problem and solved it?

<img width="1390" alt="Captura de Pantalla 2021-05-12 a la(s) 17 21 10" src="https://user-images.githubusercontent.com/3171027/118052531-89738a80-b348-11eb-95a9-589b39819eef.png">

Thanks

**Comment by anuranduttaroy** [comment]
Hey @robertbarron, this looks like the Amazon Chime Web Client which is different from the SDK. If it's the Web Client, it supports meeting recording from the app itself. There is a "record" button on the bottom left of the screen which starts the meeting recording.

**Comment by anuranduttaroy** [comment]
Hey @robertbarron feel free to re-open this if you still have questions.

**Comment by robertbarron** [comment]
Hey @anuranduttaroy , the recording button only records audio and "share screen" only. I want to record the entire sesion, but I am finding a lot of issues with Chime web client, like audio quality, black screens and more.

Thanks for your help!
