### ISSUE TITLE
Bot Recording from form page

### ISSUE THREAD

**Issue by rohit0337** [aws-samples/amazon-chime-sdk-recording-demo#90]
Hello
we added recording solution into our application. its recording the meeting but its stuck on join form page and recording all meeting from there.

**Comment by anuranduttaroy** [comment]
Hey @rohit0337

Can you share some more details about the issue. May be some ECS logs and screenshot of the issue would help.

**Comment by jing-chen1** [comment]
Closing the issue for now. Feel free to reopen it if you still have problems.
