### ISSUE TITLE
store recording to external storage instead of s3

### ISSUE THREAD

**Issue by ebony-g** [aws-samples/amazon-chime-sdk-recording-demo#92]
Hi,

I've read the document and it is stated that the record is being saved to the s3 bucket.

```Once the recording stops open the AWS Console and navigate to Amazon S3. The recording is saved in the bucket chime-meeting-sdk-<aws-account-id>-<region>-recording-artifacts with the following format: YYYY/MM/DD/HH/<ISO8601 time when meeting started>.mp4. You can now play or edit this recording, as necessary.```

Is it possible to store the record to an external storage/file server or to an AWS Elastic File Server? If yes, may I know how to implement such integration to chime SDK?

Thank you.

Regards,
Ebony

**Comment by anuranduttaroy** [comment]
Hey @ebony-g, unfortunately in this demo, we are only uploading the recording artifacts to Amazon S3 using this [S3Uploader class](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/utils/upload.js#L10) and using it here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L77. 

If you want to upload it to some other destination like AWS Elastic File Server or Kinesis Video Stream, you would have to write a custom uploader which takes the output from `ffmpeg` [here](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L25) from the recorded stream and writes it to the destination you want.

**Comment by tenge-amzn** [comment]
Chime SDK team has launched a new service to provide meeting capture capabilities with original video resolution and frame rate. You will not need to provision your own container infrastructure. Instead, just call the API from AWS SDK and provide a prepared S3 bucket to receive the artifacts. 

To know more, please check out the blog:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
