### ISSUE TITLE
where to locate files when deployed at ec2 instance

### ISSUE THREAD

**Issue by ebony-g** [aws-samples/amazon-chime-sdk-recording-demo#93]
Hi,

I am looking for the files when it is deployed at ec2. I tried to upload/save the file at ec2 instead of sending it directly to s3 however, I cannot find a way on where it is being saved.

Can you point to me where it is located?

Thank you.

**Comment by tenge-amzn** [comment]
Chime SDK team has launched a new service to provide meeting capture capabilities with original video resolution and frame rate. You will not need to provision your own container infrastructure. Instead, just call the API from AWS SDK and provide a prepared S3 bucket to receive the artifacts. 

To know more, please check out the blog:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
