### ISSUE TITLE
Readme Information is not accurate

### ISSUE THREAD

**Issue by ArtmisL** [aws-samples/amazon-chime-sdk-recording-demo#96]
I deployed the Amazon Chime SDK Serverless demo and proceeded to make meeting however upon copying the url to the new tab it asks for name and information and does not automatically join. This is an issue for testing the recording demo.

Am I missing something?

**Comment by anuranduttaroy** [comment]
Hey @ArtmisL, are you trying to test how the recording bot joins the meeting automatically by pasting the URL in the browser?

For that, you need to append `record=true` param in the URL. Here is an example of the URL

```
https://abcdefgh.execute-api.us-east-1.amazonaws.com/Prod/?m=SomeMeetingID&record=true
```

Let me know if this answers your question.

**Comment by jing-chen1** [comment]
Closing the issue. Feel free to reopen it if you still have problems.
