### ISSUE TITLE
There is significant delay between audio and video

### ISSUE THREAD

**Issue by paul365** [aws-samples/amazon-chime-sdk-recording-demo#99]
Hi, Do you guys know what might cause a delay between the audio and video in the recording file? Thanks!

**Comment by devalevenkatesh** [comment]
Hello @paul365 ,

Thanks for reporting this issue. I see we have had few closed issue who ran into similar problems.

From #38 issue, could you please check if [this comment](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/38#issuecomment-685148540) works for you. There is a PR for the same if you can try that out as well: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/pull/80/files

**Comment by jing-chen1** [comment]
Closing the issue. Feel free to reopen if you still have problems.
